server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ead-course
    username: course
    password: course
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  application:
    name: ead-course-service

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEventExchange: ead.userevent
      notificationCommandExchange: ead.notificationcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.course
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
